### ISSUE TITLE
List your org site as a Brave Content Creator

### ISSUE THREAD

**Issue by PioArchiver** [Konjure/konjure-org#1]
BAT tokens maybe a vital way you guys can receive funding for your project, and is relatively easy to do. You can find information about the Brave Browser Program at this link https://creators.brave.com/ 

It would give supporters a easy way to spread there BAT to you and also help them earn more BAT to spread around just by visiting and staying engaged with your project too.

Also you get a handy link to help people learn about Brave Browser and yourself earn more by spreading the word, here is my link
https://brave.com/kip631

**Comment by KaiMicahMills** [comment]
Thanks for bringing this up - we'll check it out!
